import{a as P,S as $,i as q}from"./assets/vendor-C4-ZuMk8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const _="46204158-4df5f152d7953f3c8acc30a03",I="https://pixabay.com/api/";async function g(t,r=1,s=15){const n=`${I}?key=${_}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${s}`;try{const{data:e}=await P.get(n);return e.hits}catch(e){throw console.error("Error fetching data:",e),e}}let y;function M(){const t=document.querySelector(".gallery");t.innerHTML=""}function p(t){const r=document.querySelector(".gallery"),s=t.map(({webformatURL:n,largeImageURL:e,tags:o,likes:c,views:v,comments:S,downloads:E})=>`
    <a class="gallery__item" href="${e}">
      <img class="gallery__image" src="${n}" alt="${o}" loading="lazy" />
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${c}</p>
        <p class="info-item"><b>Views:</b> ${v}</p>
        <p class="info-item"><b>Comments:</b> ${S}</p>
        <p class="info-item"><b>Downloads:</b> ${E}</p>
      </div>
    </a>`).join("");r.insertAdjacentHTML("beforeend",s),y?y.refresh():y=new $(".gallery a")}function i(t){q.error({title:"Error",message:t})}const A=document.querySelector(".search-form"),B=document.querySelector('input[name="searchQuery"]'),b=document.querySelector(".loader"),a=document.createElement("button");a.textContent="Load more";a.classList.add("load-more");document.body.appendChild(a);let d=1,u="";const L=15;let h=0,l=0;function w(){b.classList.add("visible")}function f(){b.classList.remove("visible")}function m(){a.style.display="none"}function C(){a.style.display="block"}m();A.addEventListener("submit",async t=>{t.preventDefault();const r=B.value.trim();if(!r){i("Please enter a search term.");return}u=r,d=1,l=0,M(),m(),w();try{const s=await g(u,d,L),n=s.hits;if(h=s.totalHits,l+=n.length,f(),n.length===0){i("Sorry, there are no images matching your search query. Please try again!");return}p(n),l<h?C():(m(),i("We're sorry, but you've reached the end of search results."))}catch{f(),i("Something went wrong. Please try again later.")}});a.addEventListener("click",async()=>{d+=1,w();try{const r=(await g(u,d,L)).hits;l+=r.length,f(),p(r),l>=h&&(m(),i("We're sorry, but you've reached the end of search results."))}catch{f(),i("Something went wrong. Please try again later.")}});function O(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}a.addEventListener("click",async()=>{await g(u,d),O()});
//# sourceMappingURL=index.js.map
