import{a as S,S as P,i as $}from"./assets/vendor-C4-ZuMk8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const q="46204158-4df5f152d7953f3c8acc30a03",_="https://pixabay.com/api/";async function g(t,r=1,n=15){const s=`${_}?key=${q}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${n}`;try{const{data:e}=await S.get(s);return e.hits}catch(e){throw console.error("Error fetching data:",e),e}}let h;function I(){const t=document.querySelector(".gallery");t.innerHTML=""}function y(t){const r=document.querySelector(".gallery"),n=t.map(({webformatURL:s,largeImageURL:e,tags:o,likes:c,views:L,comments:E,downloads:v})=>`
    <a class="gallery__item" href="${e}">
      <img class="gallery__image" src="${s}" alt="${o}" loading="lazy" />
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${c}</p>
        <p class="info-item"><b>Views:</b> ${L}</p>
        <p class="info-item"><b>Comments:</b> ${E}</p>
        <p class="info-item"><b>Downloads:</b> ${v}</p>
      </div>
    </a>`).join("");r.insertAdjacentHTML("beforeend",n),h?h.refresh():h=new P(".gallery a")}function l(t){$.error({title:"Error",message:t})}const M=document.querySelector(".search-form"),A=document.querySelector('input[name="searchQuery"]'),p=document.querySelector(".loader"),i=document.createElement("button");i.textContent="Load more";i.classList.add("load-more");document.body.appendChild(i);let a=1,u="";const d=15;let b=0;function w(){p.classList.add("visible")}function f(){p.classList.remove("visible")}function m(){i.style.display="none"}function B(){i.style.display="block"}m();M.addEventListener("submit",async t=>{t.preventDefault();const r=A.value.trim();if(!r){l("Please enter a search term.");return}u=r,a=1,I(),m(),w();try{const n=await g(u,a,d);if(!n||!n.hits)throw new Error("Invalid response format");const s=n.hits;if(b=n.totalHits,f(),s.length===0){l("Sorry, there are no images matching your search query. Please try again!");return}y(s),s.length===d?B():m()}catch(n){f(),console.error("Error fetching images:",n),l("Something went wrong. Please try again later.")}});i.addEventListener("click",async()=>{a+=1,w();try{const t=await g(u,a,d);if(!t||!t.hits)throw new Error("Invalid response format");const r=t.hits;f(),y(r),(r.length<d||a*d>=b)&&(m(),l("We're sorry, but you've reached the end of search results."))}catch(t){f(),console.error("Error fetching images:",t),l("Something went wrong. Please try again later.")}});function C(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}i.addEventListener("click",async()=>{await g(u,a),C()});
//# sourceMappingURL=index.js.map
